### ISSUE TITLE
table move multiple rows

### ISSUE THREAD

**Issue by nunob87** [David-Desmaisons/draggable-example#11]
hello, I want to move several lines together if you want the same movement, how can I do this?

Example (move group 1 all together)
tr-1
tr-1.1
tr-1.2
tr-2
tr-3
tr-3.1

thanks

**Comment by David-Desmaisons** [comment]
It is not currently supported.
Sortable.js may add this feature in the near future so stay tuned on vue.draggable updates

**Comment by nunob87** [comment]
What is the forecast for this update? I need this to finalize an update.

**Comment by David-Desmaisons** [comment]
No forecast.
This branch https://github.com/SortableJS/Sortable/tree/next-version has to be merged first.

**Comment by nunob87** [comment]
But even this version does not have what I intend, I'll see how I can develop this, thank you
