### ISSUE TITLE
Disable drop but enable drag out

### ISSUE THREAD

**Issue by pimboden** [David-Desmaisons/draggable-example#3]
Hello.
Firts of all : Nice job! Works very easy.
Now to my question:
I have 2 lists, one with available people, and one with subscribed persons.
in the subscribed-persons, i have a maximum amount of allowed subscriptions. When this amount is reached, I want to disable drop on that list. but I want to still be able to drag persons out of this list.
if I do like this:
:options="{group:'persons', disabled: subscribedPersons.length == maxSubscriptions}
I cant drop any more users in it, but the problem is that then I can't remove any person from this list either.
 I  did it programmatically with the :move binding. Is there a better way to do it?

Can you help me here?
Thanks a lot

**Comment by David-Desmaisons** [comment]
Try to use the name option, from sortable.js

> 	group: "name",  // or { name: "...", pull: [true, false, clone], put: [true, false, array] }

By changing the put value depending on the array length, it should do the trick.
