### ISSUE TITLE
Compatibility with Element's tree component?

### ISSUE THREAD

**Issue by flegascoin** [David-Desmaisons/draggable-example#4]
Hi David:

I stumbled on your work, downloaded it - looking really cool.

Before spending too much time researching it on my end - do you know if your library can be used with Element's tree component (http://element.eleme.io/#/en-US/component/tree)?

Many thanks,

Fabrice.

**Comment by David-Desmaisons** [comment]
For what I have seen this element component already have a built-in drag-and-drop, so better use it instead of vue.draggable.
