### ISSUE TITLE
is it possible to click on icon in the list to drag ? not the entire list click

### ISSUE THREAD

**Issue by achuthhadnoor** [David-Desmaisons/draggable-example#6]
now it is like we can click on list to drag and drop!
but....
can i click on an icon in the list to drag?

` <draggable class="list-group" element="ul" v-model="lists" :options="dragOptions" :move="onMove" @start="isDragging=true" @end="isDragging=false"> 
          <transition-group type="transition" :name="'flip-list'">
                    <div class="icon-list selected" v-for="list in lists" :key='list.order'>
                            
                                  <i class="faa fa-android></i>
                    </div>
          </transition-group>
      </draggable>`

in above code we can click any part of div to drag
i want to drag using an icon in it.

**Comment by David-Desmaisons** [comment]
Use draghandle. Check the documentation and dlosed issue.

**Comment by achuthhadnoor** [comment]
I actually didn't get you 😑 and u please be specific,  thanks in advance

**Comment by David-Desmaisons** [comment]
If I understand you well, you need to use handle option, check here for description https://github.com/RubaXa/Sortable
