### ISSUE TITLE
Drag the element by dragging particular icon/section

### ISSUE THREAD

**Issue by jrvaja** [David-Desmaisons/draggable-example#7]
Hey Folks,
@David-Desmaisons 
This is one of the best package developed for VueJS Drag-drop feature.

I am not sure that whether it's possible with draggable for below feature.

**Example:**
Referring your example GIF.
https://raw.githubusercontent.com/SortableJS/Vue.Draggable/master/example.gif

If I drag by using *pin* icons, then only it should be dragged not by entire element.

Let me know if need any further details in this regards.

**Comment by krugerpl** [comment]
+1 for this missing feature :)

**Comment by David-Desmaisons** [comment]
This repository is only an example usage of vue.draggable to desmostrate a bais usage.
For question on usage of vue.draggable please use stackoverflow.
